name: Sync public pages to private CV

on:
  push:
    branches: [ main ]
    paths:
      - 'index.md'
      - 'teaching.md'
      - 'research.md'
      - 'supervision.md'
      - 'service_contributions.md'
      - 'professional_activities.md'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: sync-cv-to-private
  cancel-in-progress: true

jobs:
  build-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Verify PAT secret
        run: |
          if [ -z "${{ secrets.PRIVATE_REPO_PAT }}" ] && [ -z "${{ secrets.CV_PRIVATE_PAT }}" ]; then
            echo "::error::Missing secret. Add PRIVATE_REPO_PAT (recommended) or CV_PRIVATE_PAT in Settings → Secrets and variables → Actions."
            exit 1
          fi

      - uses: actions/checkout@v4

      - name: Build out/cv.md
        run: python3 .github/scripts/build_cv.py

      - name: Clone private repo (cv-private)
        env:
          PAT1: ${{ secrets.PRIVATE_REPO_PAT }}
          PAT2: ${{ secrets.CV_PRIVATE_PAT }}
          DEST_REPO: ${{ secrets.CV_PRIVATE_REPO }}
        run: |
          set -euo pipefail
          GH_PAT="${PAT1:-${PAT2:-}}"
          [ -n "${GH_PAT}" ] || { echo "::error::No usable PAT found"; exit 1; }
          REPO_SLUG="${DEST_REPO:-avcixm/cv-private}"
          echo "[INFO] Cloning ${REPO_SLUG}"
          git clone "https://x-access-token:${GH_PAT}@github.com/${REPO_SLUG}.git" cvrepo
          cd cvrepo
          git config user.name  "github-actions"
          git config user.email "actions@github.com"

      - name: Update cv.md and push
        env:
          PAT1: ${{ secrets.PRIVATE_REPO_PAT }}
          PAT2: ${{ secrets.CV_PRIVATE_PAT }}
        run: |
          set -euo pipefail
          cp out/cv.md cvrepo/cv.md
          cd cvrepo
          git checkout main || git checkout -b main
          git pull --rebase origin main || true
          git add cv.md
          git commit -m "Sync from academicprofile ${GITHUB_SHA}" || echo "No changes to commit"
          git push origin HEAD:main
